version: '3'
services:
  node:
    container_name: hellobetter_node
    build: .
    ports:
      - 80:3000
    links:
      - mongo
    restart: always
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27018:27017"
